import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import LoginBtn from './LoginBtn'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import LogoutBtn from './LogoutBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const userSession = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href='/' className='logo'>Appleforum</Link>
          <Link href='/list'>List</Link>
          {userSession ?<LogoutBtn/> : <LoginBtn/>}
          
          {userSession && <span>{userSession.user.name}님 환영합니다.</span>}
          
        </div>
        {children}
        </body>
    </html>
  )
}
